import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
const apps=JSON.parse(readFileSync('data/apps.json','utf8'));
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arrow='<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M7 17 17 7M7 7h10v10"/></svg>';
const tone=a=>`style="--tone:${a.color};--ink:${a.ink}"`;
function page(title,description,content,base='./'){return `<!doctype html><html lang="tr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><meta name="theme-color" content="#f8f9fb"><meta property="og:type" content="website"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><link rel="icon" href="${base}favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${base}site.css"></head><body><a class="skip" href="#main">İçeriğe geç</a><div class="wrap"><header><a class="brand" href="${base}" aria-label="Cey Studios ana sayfa">cey<span>studios</span></a><nav aria-label="Ana menü"><a href="${base}#uygulamalar">Uygulamalar</a><a href="${base}#studyo">Stüdyo</a></nav></header><main id="main">${content}</main><div class="endmark" aria-hidden="true">cey studios</div><footer><p>© ${new Date().getFullYear()} Cey Studios</p><p>Günlük hayatın farklı anları için.</p><a href="${base}#uygulamalar">Uygulamaları keşfet</a></footer></div></body></html>`;}
function card(a,base='./'){return `<a class="app-card" href="${base}apps/${a.slug}/" ${tone(a)}><div class="app-visual">${a.image?`<img src="${base}assets/${a.image}" alt="" width="800" height="600" loading="lazy"><span class="overlay app-name">${escape(a.name)}</span>`:`<span class="app-name">${escape(a.name)}</span>`}</div><div class="category-label">${escape(a.category)}</div><div class="app-meta"><div><h3>${escape(a.name)}</h3><p>${escape(a.description)}</p></div>${arrow}</div></a>`;}
const home=`<section class="hero"><h1>Hayata dokunan<br><em>küçük fikirler.</em></h1><div class="intro"><p>Günlük ritüellerden yeni keşiflere.<br>Cey Studios, hayatın farklı anları için mobil uygulamalar geliştirir.</p><a class="text-link" href="#uygulamalar">Sana uygun olanı keşfet ${arrow}</a></div></section><section class="feature-wall" aria-label="Öne çıkan uygulamalar"><a class="feature fast" href="./apps/fasttrack/" style="--ink:#23351c"><div><p class="category">Oruç, su ve kilo takibi</p><h2>Kendi ritmini<br>bul.</h2></div><span class="giant" aria-hidden="true">16:8</span><div class="feature-bottom"><strong>FastTrack</strong><span class="circle">${arrow}</span></div></a><a class="feature dark" href="./apps/neurosound/" style="--tone:#172d38;--ink:#fff"><img class="feature-art" src="./assets/neurosound.jpg" alt="NeuroSound uygulamasının sakin doğa görseli" width="800" height="700"><div><p class="category">Uyku, odak ve dinlenme</p><h2>Dünyayı biraz<br>sessize al.</h2></div><div class="feature-bottom"><strong>NeuroSound</strong><span class="circle">${arrow}</span></div></a></section><section id="uygulamalar"><div class="section-head"><h2>Bir uygulama.<br>Yeni bir alışkanlık.</h2><p>Kendine iyi bakmak, odaklanmak ya da başka bir dünyaya adım atmak için.</p></div><div class="catalogue">${apps.map(a=>card(a)).join('')}</div></section><section class="studio" id="studyo"><h2>Merhaba, biz Cey.</h2><div><p>Biraz daha kolay bir gün.<br>Kendine ayırdığın bir an.<br>Merakla açtığın yeni bir kapı.</p><p class="small">Cey Studios olarak farklı ihtiyaçlar için mobil deneyimler geliştiriyoruz. Uygulamalarımızın her biri kendi dünyasına sahip; ortak noktaları günlük hayatta kendine bir yer bulmak.</p></div></section>`;
mkdirSync('dist',{recursive:true});writeFileSync('dist/index.html',page('Cey Studios | Hayata dokunan uygulamalar','Cey Studios uygulamalarını keşfet. Oruç takibi, meditasyon, ses, maneviyat ve interaktif hikâyeler.',home));
for(const a of apps){const base='../../';const content=`<a class="back" href="../../#uygulamalar">Tüm uygulamalara dön</a><section class="detail-hero" ${tone(a)}><div><div class="detail-brand">${escape(a.name)}</div><h1>${escape(a.headline)}</h1><p>${escape(a.description)}</p>${a.storeUrl?`<a class="button" href="${escape(a.storeUrl)}" target="_blank" rel="noopener noreferrer">Mağazada görüntüle ${arrow}</a>`:`<p class="availability">Mağaza bağlantısı yakında burada.</p>`}</div><div class="detail-art">${a.image?`<img src="../../assets/${a.image}" alt="${escape(a.name)} uygulamasından görsel" width="800" height="600">`:`<strong>${escape(a.name)}</strong>`}</div></section><section class="features"><h2>Neler yapabilirsin?</h2><div>${a.features.map(([h,p])=>`<div class="feature-row"><h3>${escape(h)}</h3><p>${escape(p)}</p></div>`).join('')}${a.note?`<p class="note">${escape(a.note)}</p>`:''}</div></section><section class="more"><h2>Başka bir şey keşfet.</h2><div class="catalogue">${apps.filter(b=>b.slug!==a.slug).slice(0,2).map(b=>card(b,base)).join('')}</div></section>`;mkdirSync(`dist/apps/${a.slug}`,{recursive:true});writeFileSync(`dist/apps/${a.slug}/index.html`,page(`${a.name} | Cey Studios`,a.description,content,base));}
writeFileSync('dist/404.html',page('Sayfa bulunamadı | Cey Studios','Bu sayfa bulunamadı.','<section class="hero"><h1>Burada bir sayfa yok.</h1><div class="intro"><p>Aradığın uygulamayı ana sayfadan bulabilirsin.</p><a class="button" href="/">Ana sayfaya dön</a></div></section>','/'));
writeFileSync('dist/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="16" fill="#2454e6"/><text x="16" y="48" font-family="Arial,sans-serif" font-weight="bold" font-size="52" fill="white">c</text></svg>');
console.log(`Built home, ${apps.length} app pages and 404.`);
