import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
const apps=JSON.parse(readFileSync('data/apps.json','utf8'));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arrow='<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M5 19 19 5M5 5h14v14"/></svg>';
const num=n=>String(n).padStart(2,'0');
const mark='<span class="brand-mark" aria-hidden="true">c.</span>';
const short={fasttrack:'Oruç · Su · Kilo',neurosound:'Uyku · Odak · Dinlenme',selaora:'Dua · Okuma · Şükran',ihvan:'Kur’an · Namaz · Zikir',sakin:'Nefes · Meditasyon','regl-takip':'Döngü · Belirtiler',fal:'Kahve · Tarot · Astroloji','secret-chapters':'Hikâyeler · Seçimler'};
const initials={fasttrack:'Ft',neurosound:'Ns',selaora:'Se',ihvan:'İh',sakin:'Sa','regl-takip':'Rt',fal:'Fa','secret-chapters':'Sc'};
function page(title,description,content,base='./'){return `<!doctype html><html lang="tr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#f7f7f2"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><link rel="icon" href="${base}favicon.svg" type="image/svg+xml"><link rel="preload" href="${base}assets/manrope.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="${base}site.css"><script defer src="${base}site.js"></script></head><body id="top"><a class="skip" href="#main">İçeriğe geç</a><header class="site-header shell"><a class="brand" href="${base}" aria-label="Cey Studios ana sayfa">${mark}<span>cey studios</span></a><nav aria-label="Ana menü"><a href="${base}#uygulamalar">Uygulamalar <sup>${num(apps.length)}</sup></a><a href="${base}#studyo">Stüdyo</a></nav><a class="header-cta" href="${base}#uygulamalar">Keşfet ${arrow}</a></header><main id="main">${content}</main><footer class="footer"><div class="shell"><div class="footer-top"><a class="brand" href="${base}">${mark}<span>Bir sonraki keşfine.</span></a><a class="to-top" href="#top">Başa dön ${arrow}</a></div><a href="${base}" class="footer-wordmark" aria-label="Cey Studios ana sayfa">cey studios</a><div class="footer-bottom"><span>© ${new Date().getFullYear()} Cey Studios</span><span>Mobil uygulamalar. Farklı dünyalar.</span><a href="${base}#uygulamalar">Tüm uygulamalar</a></div></div></footer></body></html>`;}
function appCard(a,i,base='./'){return `<a class="directory-card magic-card reveal" href="${base}apps/${a.slug}/" style="--app-color:${a.color};--app-ink:${a.ink}"><div class="card-top"><span class="app-monogram" aria-hidden="true">${initials[a.slug]}</span><span class="item-number">${num(i+1)}</span></div><div class="card-copy"><p class="eyebrow">${esc(a.category)}</p><h3>${esc(a.name)}</h3><p>${esc(a.description)}</p></div><div class="card-bottom"><span>Uygulamayı incele</span>${arrow}</div></a>`;}
const home=`<section class="hero shell"><div class="hero-kicker"><span class="eyebrow">Cey Studios / Mobil uygulamalar</span><span class="hero-index">Farklı ihtiyaçlar. Tek stüdyo.</span></div><h1>Küçük ekranlar.<br><em>Büyük dünyalar.</em></h1><div class="hero-bottom"><a class="round-link" href="#uygulamalar" aria-label="Uygulamaları keşfet">${arrow}</a><p>Bir alışkanlık edin. Biraz yavaşla.<br>Ya da başka bir hikâyeye adım at.<br><strong>Günün nereye giderse, yanında.</strong></p><span class="hero-caption"><span>${num(apps.length)}</span> uygulama,<br>kendine ayırdığın zaman için.</span></div></section>
<section class="showcase shell" aria-label="Öne çıkan uygulamalar"><div class="bento-grid"><a class="showcase-card sound reveal" href="./apps/neurosound/"><img src="./assets/neurosound.jpg" alt="" width="1774" height="887" fetchpriority="high"><div class="showcase-top"><span class="capsule">NeuroSound</span><span class="project-number">01 / SES & ODAK</span></div><div class="showcase-copy"><span class="eyebrow">Dünyanın sesini kıs.</span><h2>Kendine<br>kulak ver.</h2><div class="showcase-foot"><p>Uyku, odak ve dinlenme için<br>kendi ses ortamını oluştur.</p><span class="circle-arrow">${arrow}</span></div></div></a><a class="showcase-card fasting reveal" href="./apps/fasttrack/"><div class="showcase-top"><span class="capsule">FastTrack</span><span class="project-number">02 / GÜNLÜK RİTİM</span></div><div class="fasting-type" aria-hidden="true"><span>16<span class="colon">:</span>8</span><small>Kendi zamanında.</small></div><div class="showcase-foot"><div><h2>İyi alışkanlıklar,<br>senin ritminde.</h2><p>Oruç, su ve kilo takibi.</p></div><span class="circle-arrow">${arrow}</span></div></a><a class="showcase-card prayer reveal" href="./apps/selaora/"><img src="./assets/selaora.webp" alt="" width="1024" height="614" loading="lazy"><div class="showcase-top"><span class="capsule">Selaora</span><span class="project-number">03 / KENDİNE BİR AN</span></div><div class="showcase-foot"><div><h2>Günün içinde<br>bir durak.</h2><p>Dua, okumalar ve şükran günlüğü.</p></div><span class="circle-arrow">${arrow}</span></div></a></div></section>
<section class="catalogue-section shell" id="uygulamalar"><div class="section-heading reveal"><div><span class="eyebrow section-label">01 — Uygulamalarımız</span><h2>Sana bir dünya<br><em>ayırdık.</em></h2></div><p>Günlük rutinlerden hayal dünyalarına.<br>İlgini çekeni bul, yakından tanı.</p></div><div class="directory-grid">${apps.map((a,i)=>appCard(a,i)).join('')}</div></section>
<section class="studio" id="studyo"><div class="shell studio-grid"><div class="studio-intro reveal"><span class="eyebrow section-label">02 — Stüdyo</span><h2>Bir fikrin<br>gününe<br><em>karıştığı yer.</em></h2></div><div class="studio-copy reveal"><p class="studio-lead">Telefonunda yer açmaya<br>değecek şeyler yapıyoruz.</p><p>Bazen bir oruç sayacı. Bazen odaklanırken açtığın bir ses. Bazen de sonunu senin yazdığın bir hikâye.</p><p>Cey Studios’ta farklı ihtiyaçlar için mobil uygulamalar geliştiriyoruz. Her birinin kendi karakteri var. Hepsinin çıkış noktası aynı: günlük hayatında kullanmak isteyeceğin bir deneyim.</p><a class="line-link" href="#uygulamalar">Uygulamalarla tanış ${arrow}</a></div></div></section>`;
mkdirSync('dist',{recursive:true});
writeFileSync('dist/index.html',page('Cey Studios — Küçük ekranlar. Büyük dünyalar.','Cey Studios mobil uygulamaları: günlük alışkanlıklar, odak, maneviyat ve interaktif hikâyeler. Kendine yeni bir dünya keşfet.',home));
for(const [i,a] of apps.entries()){
const base='../../';
const visual=a.image?`<img src="${base}assets/${a.image}" alt="${esc(a.name)} görsel dünyası" width="1000" height="700"><span class="visual-caption">${esc(short[a.slug])}</span>`:`<div class="typographic-art"><span class="art-index">CEY STUDIOS / ${num(i+1)}</span><strong>${initials[a.slug]}<span>.</span></strong><span class="art-name">${esc(a.name)}</span><span class="art-category">${esc(short[a.slug])}</span></div>`;
const content=`<div class="shell"><a class="back" href="${base}#uygulamalar"><span aria-hidden="true">←</span> Tüm uygulamalar</a><section class="detail-hero" style="--app-color:${a.color};--app-ink:${a.ink}"><div class="detail-copy reveal"><span class="eyebrow">${esc(a.category)}</span><p class="detail-name">${esc(a.name)}</p><h1>${esc(a.headline)}</h1><p class="detail-description">${esc(a.description)}</p>${a.storeUrl?`<a class="button" href="${esc(a.storeUrl)}" target="_blank" rel="noopener noreferrer">Mağazada görüntüle ${arrow}</a>`:'<div class="availability"><span>Mağaza bağlantısı yakında</span><small>Uygulamayı burada yakından tanıyabilirsin.</small></div>'}</div><div class="detail-art reveal">${visual}</div></section><section class="features"><div><span class="eyebrow section-label">Uygulamanın içinde</span><h2>Gününe<br>neler katar?</h2></div><div>${a.features.map(([h,p],j)=>`<div class="feature-row reveal"><span class="item-number">${num(j+1)}</span><div><h3>${esc(h)}</h3><p>${esc(p)}</p></div></div>`).join('')}${a.note?`<p class="note">${esc(a.note)}</p>`:''}</div></section><section class="more"><div class="section-heading"><h2>Keşfetmeye<br><em>devam et.</em></h2><a class="line-link" href="${base}#uygulamalar">Tüm uygulamalar ${arrow}</a></div><div class="directory-grid">${[apps[(i+1)%apps.length],apps[(i+2)%apps.length]].map(b=>appCard(b,apps.indexOf(b),base)).join('')}</div></section></div>`;
mkdirSync(`dist/apps/${a.slug}`,{recursive:true});writeFileSync(`dist/apps/${a.slug}/index.html`,page(`${a.name} — Cey Studios`,a.description,content,base));}
writeFileSync('dist/404.html',page('Sayfa bulunamadı — Cey Studios','Aradığın uygulamayı Cey Studios’ta keşfet.','<section class="hero shell"><span class="eyebrow">404 / Sayfa bulunamadı</span><h1>Yeni bir yoldan<br><em>devam edelim.</em></h1><a class="button" href="/">Ana sayfaya dön</a></section>','/'));
console.log(`Built home, ${apps.length} app pages and 404.`);
